INPUT_FILE_NAME = 'input/input1.mid'
OUTPUT_FILE_NAME = 'output/output1.mid'

MAJOR_TRIAD = [0, 4, 7]
MINOR_TRIAD = [0, 3, 7]
DIM_CHORD = [0, 3, 6]
CHORDS_LIST = [MINOR_TRIAD, MAJOR_TRIAD, DIM_CHORD]
CONSONANT_CHORDS = []

DURATION = None
SCALE = None
MAX_NOTE = 120
POPULATION_SIZE = 128
